OnlineShop/OnlineShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('store/', include("store.urls")),
    path('cart/', include("cart.urls")),
]+ static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

OnlineShop/cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
       path("", views.cart, name="cart"),
       path('add_cart/<product_id>/', views.add_cart, name='add_cart'),

]

OnlineShop/store/urls.py
from django.urls import path
from . import views

app_name = "store"

urlpatterns = [
       path("", views.store, name="store_page"),
       path('<category_slug>/', views.store, name='products_by_category'),
       path('<category_slug>/<product_slug>/', views.product_details, name='product_details'),
]

OnlineShop/cart/models.py
from django.db import models
from store.models import Product

# Create your models here.


class Cart(models.Model):
    cart_id     = models.CharField(max_length=250, blank=True)
    date_added  = models.DateField (auto_now_add=True)
    
    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    product    = models. ForeignKey (Product, on_delete=models.CASCADE)
    cart       = models.ForeignKey (Cart, on_delete=models.CASCADE)
    quantity   = models.IntegerField()
    is_active  = models. BooleanField (default=True)

    def sub_total (self):
        return self.product.price * self.quantity
    
    def __str__(self):
        return self.product

OnlineShop/store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse

# Create your models here.

class Product (models.Model):
    product_name        = models.CharField(max_length=200, unique=True)
    slug                = models.SlugField (max_length=200, unique=True)
    description         = models.TextField(max_length=500, blank=True)
    price               = models.IntegerField()
    images              = models.ImageField (upload_to='photos/products')
    stock               = models.IntegerField()
    is_available        = models.BooleanField (default=True)
    category            = models.ForeignKey (Category, on_delete=models.CASCADE)
    created_date        = models.DateTimeField (auto_now_add=True)
    modified_date       = models.DateTimeField (auto_now=True)



    def __str__(self):
        return self.product_name

OnlineShop/cart/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from store.models import Product
from .models import Cart, CartItem


# Create your views here.


def _cart_id(request): # private function
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart (request, product_id):
    product = Product.objects.get(id=product_id) # get the product
    try:
        cart = Cart.objects.get (cart_id=_cart_id (request)) # get the cart using the cart_id present in the session
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
        cart_id = _cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        cart_item.quantity += 1 # cart_item.quantity cart_item.quantity + 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item= CartItem.objects.create(
        product = product,
        quantity = 1,
        cart = cart,
        )
        cart_item.save()
    return redirect('cart:cart')


def cart (request, total=0, quantity=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
    except Cart.ObjectNotExist:
        pass #just ignore

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
    }
    return render (request, 'store/cart.html', context)

OnlineShop/store/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest, HttpResponse
from .models import Product
from category.models import Category



# Create your views here.


def store(request : HttpRequest, category_slug=None):
   categories = None
   products = None

   if category_slug != None:
      categories = get_object_or_404(Category, slug=category_slug)
      products = Product.objects.filter (category=categories, is_available=True)
      product_count = products.count()
   else:
      products = Product.objects.all().filter(is_available=True)
      product_count = products.count()

   context = {
      'products': products,
      'product_count': product_count
   }
   return  render(request, "store/store.html", context)



def product_details(request : HttpRequest, category_slug, product_slug):
   try:
      single_product = Product.objects.get(category__slug=category_slug, slug=product_slug)#why we need category_slug here?
   except Exception as e:
      raise e
   
   context = {
      'single_product' : single_product
   }
   return render(request, "store/product_details.html", context)

OnlineShop/store/templates/store/cart.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}  Cart   {% endblock %}



{% block content %}


<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    
    <div class="row">
        <aside class="col-lg-9">
    <div class="card">
    <table class="table table-borderless table-shopping-cart">
    <thead class="text-muted">
    <tr class="small text-uppercase">
      <th scope="col">Product</th>
      <th scope="col" width="120">Quantity</th>
      <th scope="col" width="120">Price</th>
      <th scope="col" class="text-right" width="200"> </th>
    </tr>
    </thead>
    <tbody>
        {% for cart_item in cart_items %}
        <tr>
            <td>
                <figure class="itemside align-items-center">
                    <div class="aside"><img src="{{ cart_item.product.images.url }}" class="img-sm"></div>
                    <figcaption class="info">
                        <a href="#" class="title text-dark">{{ cart_item.product.product_name }}</a>
                        <p class="text-muted small">Matrix: 25 Mpx <br> Brand: Canon</p>
                    </figcaption>
                </figure>
            </td>
            <td> 
                <!-- col.// -->
                            <div class="col"> 
                                <div class="input-group input-spinner">
                                    <div class="input-group-prepend">
                                    <button class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </button>
                                    </div>
                                    <input type="text" class="form-control"  value="{{ cart_item.quantity }}">
                                    <div class="input-group-append">
                                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="btn btn-light" type="button" id="button-minus"> <i class="fa fa-plus"></i> </a>
                                    </div>
                                </div> <!-- input-group.// -->
                            </div> <!-- col.// -->
            </td>
            <td> 
                <div class="price-wrap"> 
                    <var class="price">{{ cart_item.sub_total }}</var> 
                    <small class="text-muted"> $ {{ cart_item.product.price }} each </small> 
                </div> <!-- price-wrap .// -->
            </td>
            <td class="text-right"> 
            <a href="" class="btn btn-danger"> Remove</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <aside class="col-lg-3">
    
            <div class="card">
            <div class="card-body">
                <dl class="dlist-align">
                  <dt>Total price:</dt>
                  <dd class="text-right">${{total}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Tax:</dt>
                  <dd class="text-right"> $10.00</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Total:</dt>
                  <dd class="text-right text-dark b"><strong>$59.97</strong></dd>
                </dl>
                <hr>
                <p class="text-center mb-3">
                    <img src="{% static './images/misc/payments.png' %}" height="26">
                </p>
                <a href="./place-order.html" class="btn btn-primary btn-block"> Checkout </a>
                <a href="./store.html" class="btn btn-light btn-block">Continue Shopping</a>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
    
    </aside> <!-- col.// -->
    
    
    </div> <!-- row.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

OnlineShop/store/templates/store/product_details.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}  Product Details   {% endblock %}



{% block content %}

<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
<div class="card">
	<div class="row no-gutters">
		<aside class="col-md-6">
<article class="gallery-wrap"> 
	<div class="img-big-wrap">
	   <a href="#"><img src="{{ single_product.images.url }}"></a>
	</div> <!-- img-big-wrap.// -->
	
</article> <!-- gallery-wrap .end// -->
		</aside>
		<main class="col-md-6 border-left">
<article class="content-body">

<h2 class="title">{{ single_product.product_name }}</h2>

<div class="mb-3"> 
	<var class="price h4">{{ single_product.price}}</var> 
</div> 

<p>{{ single_product.description }}</p>


<hr>
	<div class="row">
		<div class="item-option-select">
			<h6>Choose Color</h6>
			<div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
			  <label class="btn btn-light">
			    <input type="radio" name="radio_color"> Silver
			  </label>
			  <label class="btn btn-light">
			    <input type="radio" name="radio_color" > Gray
			  </label>
			  <label class="btn btn-light active">
			    <input type="radio" name="radio_color checked"> Gold
			  </label>
			  <label class="btn btn-light">
			    <input type="radio" name="radio_color"> Black
			  </label>
			</div> 
		</div>
	</div> <!-- row.// -->
	<div class="row">
		<div class="item-option-select">
			<h6>Select Size</h6>
			<div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
			  <label class="btn btn-light">
			    <input type="radio" name="radio_color"> S
			  </label>
			  <label class="btn btn-light active">
			    <input type="radio" name="radio_color" checked> M
			  </label>
			  <label class="btn btn-light">
			    <input type="radio" name="radio_color"> L
			  </label>
			  <label class="btn btn-light">
			    <input type="radio" name="radio_color"> XL
			  </label>
			</div> 
		</div>
	</div> <!-- row.// -->
	<hr>
	<h5></h5>
	{% if single_product.stock <= 0 %}
		<h5 class="text-danger">Out of stock</h5>
	{% else %}
		<a href="{% url 'cart:add_cart' single_product.id %}" class="btn btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </a>
	{% endif %}
</article> <!-- product-info-aside .// -->
		</main> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- card.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

<br>

<div class="row">
			<div class="col-md-9">

	<header class="section-heading">
		<h3>Customer Reviews </h3>  
		
	</header>

	<article class="box mb-3">
		<div class="icontext w-100">
			<img src="./images/avatars/avatar1.jpg" class="img-xs icon rounded-circle">
			<div class="text">
				<span class="date text-muted float-md-right">24.04.2020 </span>  
				<h6 class="mb-1">Mike John </h6>
				
			</div>
		</div> <!-- icontext.// -->
		<div class="mt-3">
			<p>
				Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip
			</p>	
		</div>
	</article>

	

	</div> <!-- col.// -->
</div> <!-- row.// -->


</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

OnlineShop/store/templates/store/store.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}  Store   {% endblock %}



{% block content %}

    <!-- ========================= SECTION PAGETOP ========================= -->
    <section class="section-pagetop bg">
        <div class="container">
            <h2 class="title-page">Our Store</h2>
            
        </div> <!-- container //  -->
    </section>
    <!-- ========================= SECTION INTRO END// ========================= -->

    
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
    <div class="container">
    
    <div class="row">
        <aside class="col-md-3">
            
    <div class="card">
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Categories</h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_1" style="">
                <div class="card-body">
                    
                    <ul class="list-menu">
                        <li><a href="{% url 'store:store_page' %}">All Products</a></li>
                         {% for category in links %}
                        <li><a href="{% url 'store:products_by_category' category.slug %}">{{ category.category_name }}</a></li>
                         {% endfor %}
                    </ul>
    
                </div> <!-- card-body.// -->
            </div>
        </article> <!-- filter-group  .// -->
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_4" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Sizes </h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_4" style="">
                <div class="card-body">
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> XS </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> SM </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> LG </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> XXL </span>
                  </label>
            </div><!-- card-body.// -->
            </div>
        </article> <!-- filter-group .// -->
        
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Price range </h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_3" style="">
                <div class="card-body">
                    
                    <div class="form-row">
                    <div class="form-group col-md-6">
                      <label>Min</label>
                      <!-- <input class="form-control" placeholder="$0" type="number"> -->
                          <select class="mr-2 form-control">
                            <option value="0">$0</option>
                            <option value="50">$50</option>
                            <option value="100">$100</option>
                            <option value="150">$150</option>
                            <option value="200">$200</option>
                            <option value="500">$500</option>
                            <option value="1000">$1000</option>
                        </select>
                    </div>
                    <div class="form-group text-right col-md-6">
                      <label>Max</label>
                          <select class="mr-2 form-control">
                            <option value="50">$50</option>
                            <option value="100">$100</option>
                            <option value="150">$150</option>
                            <option value="200">$200</option>
                            <option value="500">$500</option>
                            <option value="1000">$1000</option>
                            <option value="2000">$2000+</option>
                        </select>
                    </div>
                    </div> <!-- form-row.// -->
                    <button class="btn btn-block btn-primary">Apply</button>
                </div><!-- card-body.// -->
            </div>
        </article> <!-- filter-group .// -->
        
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <main class="col-md-9">
    
    <header class="border-bottom mb-4 pb-3">
            <div class="form-inline">
                <span class="mr-md-auto"><b>{{product_count}}</b> Items found </span>
                
            </div>
    </header><!-- sect-heading -->
    
    <div class="row">
        {% for product in products %}
        <div class="col-md-4">
            <figure class="card card-product-grid">
                <div class="img-wrap"> 
                    
                    <a href="{% url 'store:product_details' product.category.slug product.slug %}" ><img  src="{{ product.images.url }}"></a>
                    
                </div> <!-- img-wrap.// -->
                <figcaption class="info-wrap">
                    <div class="fix-height">
                        <a href="{% url 'store:product_details' product.category.slug product.slug %}" class="title">{{ product.product_name }}</a>
                        <div class="price-wrap mt-2">
                            <span class="price">{{ product.price }}</span>
                            <del class="price-old">$1980</del>
                        </div> <!-- price-wrap.// -->
                    </div>
                    <a href="#" class="btn btn-block btn-primary">Add to cart </a>
                </figcaption>
            </figure>
        </div> <!-- col.// -->
        {% endfor %}
    </div> <!-- row end.// -->
    
    
    <nav class="mt-4" aria-label="Page navigation sample">
      <ul class="pagination">
        <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
        <li class="page-item active"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item"><a class="page-link" href="#">Next</a></li>
      </ul>
    </nav>
    
        </main> <!-- col.// -->
    
    </div>
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}